import type { Metadata } from "next";
import { QueryClientProvider } from '@tanstack/react-query';

import "./globals.css";
import { queryClient } from '@/lib/react-query';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <QueryClientProvider client={queryClient}> */}
        <body>{children}</body>
      {/* </QueryClientProvider> */}
    </html>
  );
}
